load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(features = ["layering_check"])

cc_library(
    name = "routes",
    srcs = ["routes.cc"],
    hdrs = ["routes.h"],
    copts = ["-std=c++20"],
    implementation_deps = [
        "//:api_error",
        "//:discovery_document",
        "//:httplib",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = ["@nlohmann_json//:json"],
)

cc_library(
    name = "requests",
    srcs = ["requests.cc"],
    hdrs = ["requests.h"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":routes",
        "//:api_error",
        "//:httplib",
        "//:query_parameters",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = [
        "//:emulator",
        "//:field_schema",
        "//:references",
        "//:table_metadata",
        "@nlohmann_json//:json",
    ],
)

cc_library(
    name = "resources",
    srcs = ["resources.cc"],
    hdrs = ["resources.h"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":requests",
        "//:api_error",
        "//:emulator",
        "//:field_schema",
        "//:project",
        "//:references",
        "//:table_metadata",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = ["@nlohmann_json//:json"],
)
