load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "bignumeric",
    srcs = ["bignumeric.cc"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":register",
        ":scalar",
        "//:backend_interface",
        "//:bignumeric",
        "//:duckdb_handle",
        "//third_party/duckdb",
        "@googlesql//googlesql/base:status",
        "@googlesql//googlesql/public:numeric_value",
        "@googlesql//googlesql/public/functions:arithmetics",
        "@googlesql//googlesql/public/functions:convert",
        "@googlesql//googlesql/public/functions:convert_string",
        "@googlesql//googlesql/public/functions:generate_array",
        "@googlesql//googlesql/public/functions:math",
        "@googlesql//googlesql/public/functions:numeric",
        "@googlesql//googlesql/public/functions:rounding_mode_cc_proto",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = [":bignumeric_interface"],
)

cc_library(
    name = "math",
    srcs = ["math.cc"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":register",
        ":scalar",
        "//:duckdb_handle",
        "//third_party/duckdb",
        "@googlesql//googlesql/base:status",
        "@googlesql//googlesql/public:numeric_value",
        "@googlesql//googlesql/public/functions:arithmetics",
        "@googlesql//googlesql/public/functions:generate_array",
        "@googlesql//googlesql/public/functions:math",
        "@googlesql//googlesql/public/functions:numeric",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = [":math_interface"],
)

cc_library(
    name = "string",
    srcs = ["string.cc"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":register",
        ":scalar",
        "//:duckdb_handle",
        "//third_party/duckdb",
        "@googlesql//googlesql/base:status",
        "@googlesql//googlesql/public:numeric_value",
        "@googlesql//googlesql/public/functions:convert_string",
        "@googlesql//googlesql/public/functions:distance",
        "@googlesql//googlesql/public/functions:hash",
        "@googlesql//googlesql/public/functions:net",
        "@googlesql//googlesql/public/functions:normalize_mode_cc_proto",
        "@googlesql//googlesql/public/functions:regexp",
        "@googlesql//googlesql/public/functions:string",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = [":string_interface"],
)

cc_library(
    name = "datetime",
    srcs = ["datetime.cc"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":register",
        ":scalar",
        "//:bignumeric",
        "//:duckdb_handle",
        "//third_party/duckdb",
        "@googlesql//googlesql/base:status",
        "@googlesql//googlesql/public:civil_time",
        "@googlesql//googlesql/public:options_cc_proto",
        "@googlesql//googlesql/public:value",
        "@googlesql//googlesql/public/functions:date_time_util",
        "@googlesql//googlesql/public/functions:parse_date_time",
        "@googlesql//googlesql/public/functions:string_format",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = [":datetime_interface"],
)

cc_library(
    name = "json",
    srcs = ["json.cc"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":datetime",
        ":register",
        ":scalar",
        "//:bignumeric",
        "//:catalog",
        "//:duckdb_handle",
        "//third_party/duckdb",
        "@googlesql//googlesql/base:status",
        "@googlesql//googlesql/public:json_value",
        "@googlesql//googlesql/public:language_options",
        "@googlesql//googlesql/public:numeric_value",
        "@googlesql//googlesql/public:options_cc_proto",
        "@googlesql//googlesql/public:type",
        "@googlesql//googlesql/public:value",
        "@googlesql//googlesql/public/functions:json",
        "@googlesql//googlesql/public/functions:json_format",
        "@googlesql//googlesql/public/functions:json_internal",
        "@googlesql//googlesql/public/functions:to_json",
        "@googlesql//googlesql/public/types",
        "@nlohmann_json//:json",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = [":json_interface"],
)

cc_library(
    name = "aead",
    srcs = ["aead.cc"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":register",
        ":scalar",
        "//third_party/duckdb",
        "@boringssl//:crypto",
        "@googlesql//googlesql/base:status",
        "@protobuf//third_party/utf8_range:utf8_validity",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = [":aead_interface"],
)

cc_library(
    name = "percentile",
    srcs = ["percentile.cc"],
    copts = ["-std=c++20"],
    implementation_deps = [
        ":register",
        ":scalar",
        "//:duckdb_handle",
        "//third_party/duckdb",
        "@googlesql//googlesql/base:status",
        "@googlesql//googlesql/public:numeric_value",
        "@googlesql//googlesql/public/functions:percentile",
    ],
    linkstatic = True,
    visibility = ["//:__pkg__"],
    deps = [":percentile_interface"],
)

cc_library(
    name = "register",
    srcs = ["register.cc"],
    copts = ["-std=c++20"],
    implementation_deps = [
        "//:backend_interface",
        "//:duckdb_handle",
    ],
    linkstatic = True,
    deps = [":register_interface"],
)

cc_library(
    name = "scalar",
    hdrs = ["scalar.h"],
    deps = [
        "//:duckdb_handle",
        "@googlesql//googlesql/base:status",
    ],
)

cc_library(
    name = "register_interface",
    hdrs = ["register.h"],
    deps = ["//third_party/duckdb"],
)

cc_library(
    name = "bignumeric_interface",
    hdrs = ["bignumeric.h"],
    deps = ["//third_party/duckdb"],
)

cc_library(
    name = "math_interface",
    hdrs = ["math.h"],
    deps = ["//third_party/duckdb"],
)

cc_library(
    name = "string_interface",
    hdrs = ["string.h"],
    deps = ["//third_party/duckdb"],
)

cc_library(
    name = "datetime_interface",
    hdrs = ["datetime.h"],
    deps = [
        "//third_party/duckdb",
        "@googlesql//googlesql/base:status",
        "@googlesql//googlesql/public:civil_time",
    ],
)

cc_library(
    name = "json_interface",
    hdrs = ["json.h"],
    deps = ["//third_party/duckdb"],
)

cc_library(
    name = "aead_interface",
    hdrs = ["aead.h"],
    deps = ["//third_party/duckdb"],
)

cc_library(
    name = "percentile_interface",
    hdrs = ["percentile.h"],
    deps = ["//third_party/duckdb"],
)
