// Command storageprobe exercises the Storage v1 RPCs and generates docs/storage.md.
// It checks execution only; client-visible results belong in tests/e2e/storage.
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"time"

	"cloud.google.com/go/bigquery"
	"cloud.google.com/go/bigquery/storage/apiv1/storagepb"
	"github.com/johejo/bigquery-emulator-duckdb/internal/emulatorprocess"
	"google.golang.org/api/option"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

func main() {
	binary := flag.String("emulator", "bazel-bin/bigquery-emulator-duckdb", "emulator binary")
	flag.Parse()
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	if err := run(ctx, *binary); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(ctx context.Context, binary string) error {
	p, err := emulatorprocess.Start(ctx, binary, "", "--host", "127.0.0.1", "--port", "0", "--project", `{"projectId":"storage-probe"}`)
	if err != nil {
		return err
	}
	defer p.Stop()
	rest, err := bigquery.NewClient(ctx, "storage-probe", option.WithEndpoint(p.URL), option.WithoutAuthentication())
	if err != nil {
		return err
	}
	defer rest.Close()
	if err := rest.Dataset("probe").Create(ctx, nil); err != nil {
		return err
	}
	if err := rest.Dataset("probe").Table("rows").Create(ctx, &bigquery.TableMetadata{Schema: bigquery.Schema{{Name: "value", Type: bigquery.StringFieldType}}}); err != nil {
		return err
	}
	conn, err := grpc.NewClient(p.GRPC, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return err
	}
	defer conn.Close()
	read, write := storagepb.NewBigQueryReadClient(conn), storagepb.NewBigQueryWriteClient(conn)
	path := "projects/storage-probe/datasets/probe/tables/rows"
	descriptor := &descriptorpb.DescriptorProto{Name: proto.String("Row"), Field: []*descriptorpb.FieldDescriptorProto{{Name: proto.String("value"), Number: proto.Int32(1), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum()}}}
	appendRows := func(name string) error {
		stream, err := write.AppendRows(ctx)
		if err != nil {
			return err
		}
		if err := stream.Send(&storagepb.AppendRowsRequest{WriteStream: name, Rows: &storagepb.AppendRowsRequest_ProtoRows{ProtoRows: &storagepb.AppendRowsRequest_ProtoData{WriterSchema: &storagepb.ProtoSchema{ProtoDescriptor: descriptor}, Rows: &storagepb.ProtoRows{SerializedRows: [][]byte{[]byte("\x0a\x05probe")}}}}}); err != nil {
			return err
		}
		response, err := stream.Recv()
		if err != nil {
			return err
		}
		if response.GetError() != nil {
			return fmt.Errorf("AppendRows: %v", response.GetError())
		}
		if err := stream.CloseSend(); err != nil {
			return err
		}
		_, err = stream.Recv()
		if err != io.EOF {
			return fmt.Errorf("AppendRows close: %v", err)
		}
		return nil
	}
	fmt.Println("# BigQuery Storage API\n\nGenerated by `just docs` from `tools/storageprobe`. Probes check execution, not result compatibility.\n\n| RPC | Status | Forms and limitations |\n| --- | --- | --- |")
	for _, kind := range []storagepb.WriteStream_Type{storagepb.WriteStream_COMMITTED, storagepb.WriteStream_BUFFERED, storagepb.WriteStream_PENDING} {
		stream, err := write.CreateWriteStream(ctx, &storagepb.CreateWriteStreamRequest{Parent: path, WriteStream: &storagepb.WriteStream{Type: kind}})
		if err != nil {
			return err
		}
		if _, err := write.GetWriteStream(ctx, &storagepb.GetWriteStreamRequest{Name: stream.Name, View: storagepb.WriteStreamView_FULL}); err != nil {
			return err
		}
		if err := appendRows(stream.Name); err != nil {
			return err
		}
		if kind == storagepb.WriteStream_BUFFERED {
			if _, err := write.FlushRows(ctx, &storagepb.FlushRowsRequest{WriteStream: stream.Name, Offset: wrapperspb.Int64(0)}); err != nil {
				return err
			}
		}
		if _, err := write.FinalizeWriteStream(ctx, &storagepb.FinalizeWriteStreamRequest{Name: stream.Name}); err != nil {
			return err
		}
		if kind == storagepb.WriteStream_PENDING {
			response, err := write.BatchCommitWriteStreams(ctx, &storagepb.BatchCommitWriteStreamsRequest{Parent: path, WriteStreams: []string{stream.Name}})
			if err != nil {
				return err
			}
			if len(response.StreamErrors) != 0 {
				return fmt.Errorf("BatchCommitWriteStreams: %v", response.StreamErrors)
			}
		}
	}
	if err := appendRows(path + "/streams/_default"); err != nil {
		return err
	}
	// Partial RPCs must also exercise a valid form that is deliberately rejected.
	_, err = read.CreateReadSession(ctx, &storagepb.CreateReadSessionRequest{Parent: "projects/storage-probe", ReadSession: &storagepb.ReadSession{Table: path, DataFormat: storagepb.DataFormat_ARROW, ReadOptions: &storagepb.ReadSession_TableReadOptions{SamplePercentage: proto.Float64(50)}}})
	if status.Code(err) != codes.Unimplemented {
		return fmt.Errorf("sampling probe: %v", err)
	}
	arrow, err := write.AppendRows(ctx)
	if err != nil {
		return err
	}
	if err := arrow.Send(&storagepb.AppendRowsRequest{WriteStream: path + "/streams/_default", Rows: &storagepb.AppendRowsRequest_ArrowRows{ArrowRows: &storagepb.AppendRowsRequest_ArrowData{}}}); err != nil {
		return err
	}
	unsupported, err := arrow.Recv()
	if err != nil {
		return err
	}
	if unsupported.GetError().GetCode() != int32(codes.Unimplemented) {
		return fmt.Errorf("Arrow write probe: %v", unsupported)
	}
	if err := arrow.CloseSend(); err != nil {
		return err
	}
	if _, err := arrow.Recv(); err != io.EOF {
		return fmt.Errorf("Arrow probe close: %v", err)
	}
	for _, format := range []storagepb.DataFormat{storagepb.DataFormat_ARROW, storagepb.DataFormat_AVRO} {
		session, err := read.CreateReadSession(ctx, &storagepb.CreateReadSessionRequest{Parent: "projects/storage-probe", ReadSession: &storagepb.ReadSession{Table: path, DataFormat: format}})
		if err != nil {
			return err
		}
		for _, stream := range session.Streams {
			rows, err := read.ReadRows(ctx, &storagepb.ReadRowsRequest{ReadStream: stream.Name})
			if err != nil {
				return err
			}
			for {
				_, err := rows.Recv()
				if err == io.EOF {
					break
				}
				if err != nil {
					return err
				}
			}
			if _, err := read.SplitReadStream(ctx, &storagepb.SplitReadStreamRequest{Name: stream.Name, Fraction: 0.5}); err != nil {
				return err
			}
		}
	}
	fmt.Println("| CreateReadSession | Partial | Arrow and Avro snapshots, projection and row restrictions; historical snapshots, sampling, compression and some types unsupported |")
	fmt.Println("| ReadRows | Partial | Arrow and Avro, offsets; per-call serialization options unsupported |")
	fmt.Println("| SplitReadStream | Supported | Disjoint children of the same snapshot |")
	fmt.Println("| CreateWriteStream | Partial | COMMITTED, BUFFERED and PENDING; stream state is process-local |")
	fmt.Println("| AppendRows | Partial | Protobuf rows, default and explicit streams, offsets; Arrow input, defaults, parameterized columns, annotations, schema evolution, JSON and GEOGRAPHY unsupported |")
	fmt.Println("| GetWriteStream | Partial | BASIC and FULL; legacy default streams without table creation metadata unsupported |")
	fmt.Println("| FinalizeWriteStream | Supported | Explicit streams, including repeated finalization |")
	fmt.Println("| FlushRows | Supported | BUFFERED streams with an inclusive offset |")
	fmt.Println("| BatchCommitWriteStreams | Supported | Atomic commit of finalized PENDING streams |")
	return nil
}
