// Probes the methods of the BigQuery v2 REST API, as third_party/bigquery/discovery.json lists
// them, against the emulator's HTTP server and prints a Markdown report of which ones it serves.
// Each request is sent to a fresh emulator holding the fixture the methods file's setup requests
// create. A method the file gives no requests for is probed with one the probe builds from the
// method's path. A probe checks only that a request succeeds, not that the response matches
// BigQuery's; a note in the file describes behavior a probe cannot observe.

#include <unistd.h>

#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <optional>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <thread>
#include <utility>
#include <vector>

#include "httplib.h"
#include "nlohmann/json.hpp"
#include "src/emulator.h"
#include "src/server.h"
#include "tools/probe.h"

namespace bigquery_emulator_duckdb {
namespace {

using nlohmann::json;

constexpr std::string_view kDocs = "https://cloud.google.com/bigquery/docs/reference/rest/v2";

constexpr std::string_view kPreamble = R"(# REST API support

<!-- Generated by //:api_probe. Do not edit; run `just docs` to regenerate. -->

This page lists every method of the [BigQuery v2 REST API](https://cloud.google.com/bigquery/docs/reference/rest)
and whether the emulator serves it. The methods come from the discovery document in
`third_party/bigquery/discovery.json`.

`//:api_probe` sends each request in `tools/api_methods.txt` to the emulator's HTTP server,
holding dataset `test.d` with table `t (id INT64)` and a finished query job `j`. A method the file
gives no requests for is probed with one built from its path. A probe checks only that a request
succeeds, not that the response matches BigQuery's. The notes the methods file gives describe
what the emulator ignores or does differently, and the probe adds the features the emulator rejected as unsupported.

- **Supported**: every request succeeds.
- **Partial**: some requests succeed, and the emulator rejects the others as unsupported.
- **Unsupported**: the emulator does not serve the method, or rejects every request as
  unsupported.
- **Broken**: a request fails with an internal error, which is a bug.
- **Untested**: the probe's request failed for another reason.

)";

constexpr std::string_view kApiPrefix = "/bigquery/v2/";
constexpr std::string_view kUnsupported = "The emulator does not support ";

struct Request {
  std::string method;
  std::string path;
  std::string body;
};

struct Method {
  std::string id;
  std::string http_method;
  std::string flat_path;
  // What paths the method is served at: its path below the API prefix and its media upload paths.
  std::vector<std::regex> patterns;
  std::vector<Request> requests;
  std::string note;
};

// Splits "NAME | TEXT" at the first separator.
std::optional<std::pair<std::string, std::string>> SplitNamed(const std::string& text) {
  const size_t separator = text.find(" | ");
  if (separator == std::string::npos || separator == 0 || separator + 3 == text.size()) {
    return std::nullopt;
  }
  return std::pair(text.substr(0, separator), text.substr(separator + 3));
}

// "METHOD PATH [BODY]", with `$DIR` in the path or body standing for the directory the file
// directives write to.
std::optional<Request> ParseRequest(const std::string& text, const std::filesystem::path& dir) {
  std::istringstream words(text);
  Request request;
  words >> request.method >> request.path;
  std::getline(words >> std::ws, request.body);
  if (request.path.empty() || !request.path.starts_with("/")) {
    return std::nullopt;
  }
  for (std::string* field : {&request.path, &request.body}) {
    for (size_t at = field->find("$DIR"); at != std::string::npos; at = field->find("$DIR", at)) {
      field->replace(at, 4, dir.string());
      at += dir.string().size();
    }
  }
  return request;
}

// A pattern matching the paths a discovery path template such as "projects/{projectsId}/jobs"
// stands for.
std::regex PathPattern(const std::string& path) {
  static const std::regex kVariable(R"(\{[^}]+\})");
  static const std::regex kSpecial(R"([.^$|()\[\]*+?\\])");
  std::string pattern;
  std::sregex_token_iterator part(path.begin(), path.end(), kVariable, {-1, 0});
  for (; part != std::sregex_token_iterator(); ++part) {
    const std::string text = *part;
    pattern += text.starts_with("{") ? "[^/]+" : std::regex_replace(text, kSpecial, R"(\$&)");
  }
  return std::regex(pattern);
}

// The request the probe sends for a method the methods file gives none for: the method's path
// with the fixture's identifiers, and an empty body when the method takes one.
Request GeneratedRequest(const Method& method, bool has_body) {
  static const std::map<std::string, std::string> kIds = {
      {"projectsId", "test"}, {"datasetsId", "d"}, {"tablesId", "t"},
      {"jobsId", "j"},        {"queriesId", "j"},
  };
  std::string path(kApiPrefix);
  static const std::regex kVariable(R"(\{([^}]+)\})");
  std::sregex_token_iterator part(method.flat_path.begin(), method.flat_path.end(), kVariable,
                                  {-1, 1});
  for (bool variable = false; part != std::sregex_token_iterator(); ++part, variable = !variable) {
    const auto id = kIds.find(*part);
    path += !variable ? std::string(*part) : id != kIds.end() ? id->second : "x";
  }
  return {method.http_method, path, has_body ? "{}" : ""};
}

// The error a response reports: an HTTP error, or a job's or query's error in a successful
// response, as BigQuery reports those.
std::optional<std::string> ResponseError(const json& body) {
  if (body.contains("error")) {
    return body["error"].value("message", "");
  }
  if (body.contains("status") && body["status"].contains("errorResult")) {
    return body["status"]["errorResult"].value("message", "");
  }
  if (body.contains("errors") && body["errors"].is_array() && !body["errors"].empty()) {
    return body["errors"][0].value("message", "");
  }
  if (body.contains("insertErrors")) {
    return body["insertErrors"][0]["errors"][0].value("message", "");
  }
  return std::nullopt;
}

// Sends `request` to the server at `url`.
Probe Send(const std::string& url, const Request& request) {
  httplib::Client client(url);
  httplib::Request message;
  message.method = request.method;
  message.path = request.path;
  if (!request.body.empty()) {
    message.body = request.body;
    message.set_header("Content-Type", "application/json");
  }
  const httplib::Result result = client.send(message);
  if (!result) {
    throw std::runtime_error("no response to " + request.method + " " + request.path);
  }
  const std::string sent = "`" + request.method + " " + request.path + "`: ";
  // An unmatched route gets cpp-httplib's empty 404, never a BigQuery error.
  if (result->status == 404 && result->body.empty()) {
    return {Outcome::kUnsupported, ""};
  }
  // Deletes succeed with an empty body.
  if (result->status / 100 == 2 && result->body.empty()) {
    return {Outcome::kRuns, ""};
  }
  const json body = json::parse(result->body, nullptr, false);
  if (body.is_discarded()) {
    return {Outcome::kUntested, sent + "the response is not JSON"};
  }
  const std::optional<std::string> error = ResponseError(body);
  if (!error) {
    return result->status / 100 == 2
               ? Probe{Outcome::kRuns, ""}
               : Probe{Outcome::kUntested, sent + "HTTP " + std::to_string(result->status)};
  }
  const std::string message_text = FirstLine(*error);
  if (message_text.starts_with(kUnsupported)) {
    // The feature, without a hint such as "; set useLegacySql to false".
    const std::string feature = message_text.substr(kUnsupported.size());
    return {Outcome::kUnsupported, feature.substr(0, feature.find("; "))};
  }
  if (result->status >= 500) {
    return {Outcome::kFailsOnDuckDb, sent + message_text};
  }
  return {Outcome::kUntested, sent + message_text};
}

// Serves a fresh emulator for the duration of a probe.
class TestServer {
 public:
  TestServer() : server_(emulator_, {.host = "127.0.0.1", .port = 0}) {
    if (!server_.Bind()) {
      throw std::runtime_error("cannot bind a port");
    }
    thread_ = std::thread([this] { server_.Serve(); });
  }
  ~TestServer() {
    server_.Stop();
    thread_.join();
  }
  TestServer(const TestServer&) = delete;
  TestServer& operator=(const TestServer&) = delete;

  std::string url() const { return server_.root_url(); }

 private:
  Emulator emulator_;
  Server server_;
  std::thread thread_;
};

int Main(int argc, char** argv) {
  if (argc != 3) {
    std::cerr << "usage: api_probe DISCOVERY_FILE METHODS_FILE\n";
    return 2;
  }
  std::ifstream discovery_file(argv[1]);
  if (!discovery_file) {
    std::cerr << "cannot read " << argv[1] << "\n";
    return 1;
  }
  const json discovery = json::parse(discovery_file);
  // Resources in the discovery document's order, which is alphabetical, and their methods.
  std::vector<std::pair<std::string, std::vector<Method>>> resources;
  std::map<std::string, std::pair<size_t, size_t>> methods;
  // Whether each method takes a request body.
  std::map<std::string, bool> has_body;
  for (const auto& [resource, value] : discovery.at("resources").items()) {
    resources.emplace_back(resource, std::vector<Method>());
    for (const auto& [name, method] : value.at("methods").items()) {
      Method entry{.id = method.at("id"),
                   .http_method = method.at("httpMethod"),
                   .flat_path = method.at("flatPath")};
      entry.patterns.push_back(PathPattern(std::string(kApiPrefix) + entry.flat_path));
      if (method.contains("mediaUpload")) {
        for (const auto& [protocol, upload] : method["mediaUpload"]["protocols"].items()) {
          entry.patterns.push_back(PathPattern(upload.at("path")));
        }
      }
      has_body[entry.id] = method.contains("request");
      methods[entry.id] = {resources.size() - 1, resources.back().second.size()};
      resources.back().second.push_back(std::move(entry));
    }
  }

  const std::filesystem::path dir =
      std::filesystem::temp_directory_path() / ("api_probe." + std::to_string(getpid()));
  std::filesystem::create_directories(dir);
  struct RemoveDir {
    std::filesystem::path path;
    ~RemoveDir() { std::filesystem::remove_all(path); }
  } remove_dir{dir};

  std::vector<Request> setup;
  for (const auto& [directive, text] : ReadLines(argv[2])) {
    if (directive == "setup") {
      const auto request = ParseRequest(text, dir);
      if (!request) {
        std::cerr << "cannot parse: setup " << text << "\n";
        return 1;
      }
      setup.push_back(*request);
      continue;
    }
    const auto named = SplitNamed(text);
    if (!named || (directive != "file" && directive != "request" && directive != "note")) {
      std::cerr << "cannot parse: " << directive << " " << text << "\n";
      return 1;
    }
    const auto& [name, value] = *named;
    if (directive == "file") {
      std::ofstream(dir / name) << value << "\n";
      continue;
    }
    const auto found = methods.find(name);
    if (found == methods.end()) {
      std::cerr << "not a method in " << argv[1] << ": " << name << "\n";
      return 1;
    }
    Method& method = resources[found->second.first].second[found->second.second];
    if (directive == "note") {
      if (!method.note.empty()) {
        std::cerr << "second note for " << name << "\n";
        return 1;
      }
      method.note = value;
      continue;
    }
    const auto request = ParseRequest(value, dir);
    const std::string path = request ? request->path.substr(0, request->path.find('?')) : "";
    const auto matches = [&](const std::regex& pattern) { return std::regex_match(path, pattern); };
    if (!request || request->method != method.http_method ||
        std::ranges::none_of(method.patterns, matches)) {
      std::cerr << "not a request for " << name << ": " << value << "\n";
      return 1;
    }
    method.requests.push_back(*request);
  }

  std::map<std::string, int> totals;
  std::vector<std::string> untested;
  std::ostringstream body;
  for (const auto& [resource, entries] : resources) {
    body << "## " << resource << "\n\n| Method | HTTP request | Status | Notes |\n"
         << "| --- | --- | --- | --- |\n";
    for (const Method& method : entries) {
      const bool generated = method.requests.empty();
      const std::vector<Request> requests =
          generated ? std::vector{GeneratedRequest(method, has_body[method.id])} : method.requests;
      std::map<Outcome, int> counts;
      // The features the emulator rejected as unsupported, and the requests that failed.
      std::set<std::string> rejected;
      std::set<std::string> failures;
      for (const Request& request : requests) {
        const TestServer server;
        for (const Request& step : setup) {
          if (const Probe probe = Send(server.url(), step); probe.outcome != Outcome::kRuns) {
            std::cerr << "setup failed: " << step.method << " " << step.path << ": " << probe.detail
                      << "\n";
            return 1;
          }
        }
        const Probe probe = Send(server.url(), request);
        ++counts[probe.outcome];
        if (probe.outcome == Outcome::kUntested && !generated) {
          untested.push_back(method.id + ": " + probe.detail);
        } else if (probe.outcome == Outcome::kUnsupported && !probe.detail.empty()) {
          rejected.insert(probe.detail);
        } else if (probe.outcome != Outcome::kRuns && probe.outcome != Outcome::kUnsupported) {
          failures.insert(probe.detail);
        }
      }
      const std::string status = Status(counts);
      ++totals[status];
      std::string note = method.note;
      const auto append = [&note](const std::string& text) {
        note += (note.empty() ? "" : " ") + text;
      };
      std::string list;
      for (const std::string& feature : rejected) {
        list += (list.empty() ? "" : ", ") + feature;
      }
      if (!list.empty()) {
        append("Rejected as unsupported: " + list + ".");
      }
      for (const std::string& failure : failures) {
        append("Fails: " + failure + ".");
      }
      // bigquery.jobs.query is documented at jobs/query.
      const std::string name = method.id.substr(method.id.find('.') + 1);
      body << "| [`" << name << "`](" << kDocs << "/" << resource << "/"
           << name.substr(name.find('.') + 1) << ") | `" << method.http_method << " "
           << method.flat_path << "` | " << status << " | " << Escape(note) << " |\n";
    }
    body << "\n";
  }
  // Every request in the methods file is written by hand, so one that fails for a reason other
  // than the emulator's is a mistake in the file.
  if (!untested.empty()) {
    for (const std::string& message : untested) {
      std::cerr << "request failed: " << message << "\n";
    }
    return 1;
  }
  std::cout << kPreamble << "| Status | Methods |\n| --- | --- |\n";
  for (const auto& [status, count] : totals) {
    std::cout << "| " << status << " | " << count << " |\n";
  }
  std::string text = body.str();
  text.pop_back();  // The blank line after the last table.
  std::cout << "\n" << text;
  return 0;
}

}  // namespace
}  // namespace bigquery_emulator_duckdb

int main(int argc, char** argv) {
  try {
    return bigquery_emulator_duckdb::Main(argc, argv);
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  } catch (...) {
    std::cerr << "Unknown error\n";
    return 1;
  }
}
