// Probes the BigQuery functions listed in tools/bigquery_functions.txt against the emulator and
// prints a Markdown report of which ones translate and run. Each signature the analyzer knows for a
// function is called with sample arguments of its types, unless the hints file gives the calls; a
// signature the probe cannot build a valid call for is reported as untested. A probe checks only
// that a call translates and runs on DuckDB, not that it returns what BigQuery would. The hints
// file can also give a function a note on its behavior, which the report shows before the probe's
// notes.

#include <algorithm>
#include <cstddef>
#include <exception>
#include <iostream>
#include <iterator>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <variant>
#include <vector>

#include "absl/strings/ascii.h"
#include "absl/strings/str_join.h"
#include "absl/strings/str_split.h"
#include "googlesql/public/function.h"
#include "googlesql/public/function_signature.h"
#include "googlesql/public/type.h"
#include "googlesql/public/types/type_factory.h"
#include "src/catalog.h"
#include "src/emulator.h"
#include "src/field_schema.h"
#include "src/translator/functions.h"
#include "tools/probe.h"

namespace bigquery_emulator_duckdb {
namespace {

constexpr std::string_view kDocs = "https://cloud.google.com/bigquery/docs/reference/standard-sql";

constexpr std::string_view kPreamble = R"(# BigQuery function support

<!-- Generated by //:function_probe. Do not edit; run `just docs` to regenerate. -->

This page lists every function in the [BigQuery function list](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-all)
and whether the emulator runs it. The list comes from `tools/bigquery_functions.txt`, which
`tools/update_bigquery_functions.sh` scrapes from the BigQuery documentation.

`//:function_probe` calls each function once for every signature the analyzer knows, with sample
arguments of the signature's types. A function whose valid arguments the types do not describe
is called with the queries in `tools/function_probe_hints.txt` instead. A probe checks only that
a call translates and runs on DuckDB, not that it returns what BigQuery would. The notes the
hints file gives describe how the emulator follows BigQuery where DuckDB would differ, and the
probe's own notes name what it rejected.

- **Supported**: every call runs.
- **Partial**: some calls run, and the emulator rejects the others as unsupported.
- **Unsupported**: the emulator rejects every call as unsupported.
- **Broken**: a call translates but fails on DuckDB, which is a bug.
- **Untested**: the probe could not build a valid call.

The implementation column says how the emulator's function registry, in
`src/translator/functions.cc`, implements the function:

- **DuckDB function**: the DuckDB function of the same name.
- **DuckDB function, renamed**: a DuckDB function of another name.
- **DuckDB SQL**: DuckDB SQL templates, chosen by the arguments.
- **DuckDB SQL, in code**: DuckDB SQL that the translator builds in code.
- **GoogleSQL function**: GoogleSQL's own implementation, registered with DuckDB.
- **SAFE. operator**: an operator with the `SAFE.` prefix.
- **DuckDB aggregate** and **DuckDB window function**: a DuckDB aggregate or window function.

It is empty for syntax such as `CASE` and for functions the analyzer rewrites into others.

)";

class NoTables : public TableSource {
 public:
  std::optional<std::vector<FieldSchema>> FindTable(const std::string& /*project*/,
                                                    const std::string& /*dataset*/,
                                                    const std::string& /*table*/) override {
    return std::nullopt;
  }
};

// A literal of `type`, or nothing for a type BigQuery does not have.
std::optional<std::string> Sample(const googlesql::Type* type) {
  if (type->IsArray()) {
    const auto element = Sample(type->AsArray()->element_type());
    return element ? std::optional("[" + *element + "]") : std::nullopt;
  }
  if (type->IsStruct()) {
    std::string fields;
    for (const googlesql::StructField& field : type->AsStruct()->fields()) {
      const auto value = Sample(field.type);
      if (!value) {
        return std::nullopt;
      }
      fields += (fields.empty() ? "" : ", ") + *value +
                (field.name.empty() ? "" : " AS `" + field.name + "`");
    }
    return "STRUCT(" + fields + ")";
  }
  if (type->IsEnum()) {
    // Date parts are the only enum arguments BigQuery spells as keywords; it spells rounding
    // modes as strings.
    const std::string name = type->DebugString();
    if (name.find("DateTimestampPart") != std::string::npos) {
      return "DAY";
    }
    return name.find("ROUNDING_MODE") != std::string::npos
               ? std::optional<std::string>("'ROUND_HALF_EVEN'")
               : std::nullopt;
  }
  if (type->IsRange()) {
    const auto* element = type->AsRange()->element_type();
    return "RANGE<" + element->TypeName(googlesql::PRODUCT_EXTERNAL) + "> '[" +
           (element->IsDate() ? "2024-01-01, 2024-02-01"
                              : "2024-01-01 00:00:00, 2024-02-01 00:00:00") +
           ")'";
  }
  switch (type->kind()) {
    case googlesql::TYPE_INT64:
      return "2";
    case googlesql::TYPE_DOUBLE:
      return "1.5";
    case googlesql::TYPE_NUMERIC:
      return "NUMERIC '1.5'";
    case googlesql::TYPE_BIGNUMERIC:
      return "BIGNUMERIC '1.5'";
    case googlesql::TYPE_BOOL:
      return "TRUE";
    case googlesql::TYPE_STRING:
      return "'abc'";
    case googlesql::TYPE_BYTES:
      return "b'abc'";
    case googlesql::TYPE_DATE:
      return "DATE '2024-01-15'";
    case googlesql::TYPE_DATETIME:
      return "DATETIME '2024-01-15 10:20:30'";
    case googlesql::TYPE_TIME:
      return "TIME '10:20:30'";
    case googlesql::TYPE_TIMESTAMP:
      return "TIMESTAMP '2024-01-15 10:20:30+00'";
    case googlesql::TYPE_INTERVAL:
      return "INTERVAL 1 DAY";
    case googlesql::TYPE_JSON:
      return "JSON '{\"a\": [1, 2]}'";
    case googlesql::TYPE_GEOGRAPHY:
      return "ST_GEOGPOINT(1, 2)";
    default:
      return std::nullopt;
  }
}

// A sample for an argument, with templated kinds bound to INT64 (and the second template to
// STRING, so that T1 and T2 can differ).
std::optional<std::string> Sample(const googlesql::FunctionArgumentType& argument) {
  if (argument.IsConcrete() || argument.kind() == googlesql::ARG_KIND_EXPR_FIXED) {
    return argument.type() != nullptr ? Sample(argument.type()) : std::nullopt;
  }
  switch (argument.kind()) {
    case googlesql::ARG_KIND_EXPR_ANY_1:
    case googlesql::ARG_KIND_EXPR_ARBITRARY:
      return "2";
    case googlesql::ARG_KIND_EXPR_ANY_2:
    case googlesql::ARG_KIND_EXPR_STRING_ANY:
      return "'abc'";
    case googlesql::ARG_KIND_EXPR_ARRAY_ANY_1:
      return "[1, 2]";
    case googlesql::ARG_KIND_EXPR_ARRAY_ANY_2:
      return "['a', 'b']";
    case googlesql::ARG_KIND_EXPR_STRUCT_ANY:
      return "STRUCT(1 AS a)";
    case googlesql::ARG_KIND_EXPR_RANGE_ANY_1:
      return "RANGE<DATE> '[2024-01-01, 2024-02-01)'";
    default:
      return std::nullopt;
  }
}

// Whether BigQuery has the signature: GoogleSQL has signatures over types BigQuery lacks, such as
// FLOAT for CEILING.
bool IsBigQuerySignature(const googlesql::FunctionSignature& signature) {
  const googlesql::LanguageOptions& options = GoogleSqlLanguageOptions();
  if (signature.HideInSupportedSignatureList(options)) {
    return false;
  }
  const auto supported = [&](const googlesql::FunctionArgumentType& argument) {
    const googlesql::Type* type = argument.type();
    if (type != nullptr && type->IsArray()) {
      type = type->AsArray()->element_type();
    }
    return type == nullptr || (type->IsSupportedType(options) && !type->IsFloat());
  };
  return supported(signature.result_type()) &&
         std::ranges::all_of(signature.arguments(), supported);
}

// The generated query for a signature, or why there is none.
std::variant<std::string, Probe> GeneratedQuery(const std::string& name,
                                                const googlesql::Function& function,
                                                const googlesql::FunctionSignature& signature,
                                                const std::string& element = "") {
  const bool json_mutator = name == "JSON_ARRAY_APPEND" || name == "JSON_ARRAY_INSERT";
  std::vector<std::string> arguments;
  for (const googlesql::FunctionArgumentType& argument : signature.arguments()) {
    if (argument.optional() && !argument.has_argument_name()) {
      break;  // Probe the shortest form.
    }
    if (argument.optional()) {
      continue;
    }
    const auto sample =
        json_mutator && argument.type() != nullptr && argument.type()->IsString()
            ? std::optional<std::string>(name == "JSON_ARRAY_INSERT" ? "'$[0]'" : "'$'")
        : json_mutator && !element.empty() && argument.kind() == googlesql::ARG_KIND_EXPR_ARBITRARY
            ? std::optional(element)
        : !element.empty() && argument.kind() == googlesql::ARG_KIND_EXPR_ANY_1
            ? std::optional(element)
        : !element.empty() && argument.kind() == googlesql::ARG_KIND_EXPR_ARRAY_ANY_1
            ? std::optional("[" + element + "]")
            : Sample(argument);
    if (!sample) {
      return Probe{Outcome::kUntested, "no sample for " + argument.DebugString()};
    }
    arguments.push_back(*sample);
  }
  std::string call = name + "(";
  for (size_t i = 0; i < arguments.size(); ++i) {
    call += (i == 0 ? "" : ", ") + arguments.at(i);
  }
  call += ')';
  return function.IsAnalytic()    ? "SELECT " + call + " OVER (ORDER BY x) FROM UNNEST([1, 2]) AS x"
         : function.IsAggregate() ? "SELECT " + call + " FROM UNNEST([1, 2]) AS x"
                                  : "SELECT " + call;
}

// The page that documents the function itself rather than a variant of it, such as AVG over
// aggregate-dp-functions#dp_avg: the one whose anchor is the function's name.
std::string MainDoc(const std::string& name, const std::vector<std::string>& docs) {
  std::string anchor = absl::AsciiStrToLower(name);
  std::erase(anchor, '.');
  const auto doc = std::ranges::find_if(
      docs, [&](const std::string& candidate) { return candidate.ends_with("#" + anchor); });
  return doc == docs.end() ? docs.front() : *doc;
}

// The pages that document the function, which name the categories it belongs to.
std::string Categories(const std::vector<std::string>& docs) {
  std::set<std::string> pages;
  std::ranges::transform(docs, std::inserter(pages, pages.end()),
                         [](const std::string& doc) { return doc.substr(0, doc.find('#')); });
  return absl::StrJoin(pages, ", ");
}

int Main(int argc, char** argv) {
  std::vector<std::string> args(argv + 1, argv + argc);
  const bool list_signatures = std::erase(args, "--signatures") > 0;
  if (args.size() != 2) {
    std::cerr << "usage: function_probe [--signatures] FUNCTIONS_FILE HINTS_FILE\n";
    return 2;
  }
  // The pages and anchors that document each function. A name can be documented on several
  // pages, such as EXTRACT for each type it takes, and the probe covers them in one row.
  std::map<std::string, std::vector<std::string>> functions;
  for (const auto& [name, doc] : ReadLines(args.at(0))) {
    functions[name].push_back(doc);
  }
  std::map<std::string, std::vector<std::string>> hints;
  // Behavior a probe cannot observe, such as where results differ from DuckDB's defaults.
  std::map<std::string, std::string> documented;
  for (const auto& [directive, hint] : ReadLines(args.at(1))) {
    const std::string name = hint.substr(0, hint.find(' '));
    const std::string text = hint.substr(std::min(hint.size(), name.size() + 1));
    if ((directive != "query" && directive != "note") || text.empty() ||
        (directive == "note" && documented.contains(name))) {
      std::cerr << "cannot parse hint: " << directive << " " << hint << "\n";
      return 1;
    }
    // A hint for a function BigQuery does not have is a typo or a function BigQuery dropped.
    if (!functions.contains(name)) {
      std::cerr << "hint names a function not in " << args.at(0) << ": " << name << "\n";
      return 1;
    }
    if (directive == "note") {
      documented[name] = text;
    } else {
      hints[name].push_back(text);
    }
  }

  googlesql::TypeFactory type_factory;
  NoTables tables;
  BigQueryCatalog catalog(tables, &type_factory, "test", "");
  Emulator emulator("", {{.project_id = "test"}}, "jdoe@example.com");
  std::map<std::string_view, int> totals;
  std::ostringstream rows;
  for (const auto& [name, docs] : functions) {
    std::vector<Probe> probes;
    const googlesql::Function* function = nullptr;
    // Aliases such as CEILING resolve to the function they stand for.
    const std::vector<std::string> path = absl::StrSplit(name, '.');
    const bool known = catalog.FindFunction(path, &function).ok();
    // Functions spelled as syntax, such as EXTRACT, are operators such as $EXTRACT.
    const translator::FunctionEntry* entry =
        translator::FindFunction(known ? absl::AsciiStrToUpper(function->Name()) : "$" + name);
    const std::string implementation =
        entry == nullptr ? "" : std::string(translator::Describe(entry->implementation));
    if (const auto hinted = hints.find(name); hinted != hints.end()) {
      for (const std::string& sql : hinted->second) {
        // Probes execute queries, so preserve their evaluation order explicitly.
        // cppcheck-suppress useStlAlgorithm
        probes.push_back(RunProbe(emulator, tables, sql));
      }
    } else if (known) {
      for (const googlesql::FunctionSignature& signature : function->signatures()) {
        if (!IsBigQuerySignature(signature)) {
          continue;
        }
        std::vector<std::string> elements = {""};
        // These mutators take independently typed values, including containers. Probe the
        // supported JSON encoding types rather than declaring the arbitrary signature supported
        // from INT64 alone. GeneratedQuery supplies valid paths for both operations.
        if (name == "JSON_ARRAY_APPEND" || name == "JSON_ARRAY_INSERT") {
          elements = {"2",
                      "2.0",
                      "NUMERIC '2'",
                      "BIGNUMERIC '2'",
                      "TRUE",
                      "'abc'",
                      "b'abc'",
                      "DATE '2024-01-15'",
                      "TIME '10:20:30'",
                      "DATETIME '2024-01-15 10:20:30'",
                      "TIMESTAMP '2024-01-15 10:20:30+00'",
                      "INTERVAL 1 SECOND",
                      "JSON '[1]'",
                      "[1, NULL]",
                      "STRUCT(BIGNUMERIC '2' AS b)",
                      "STRUCT()",
                      "RANGE<DATE> '[2024-01-01, 2024-02-01)'"};
        }
        // Probe a point and same-typed boundaries across orderable scalar types,
        // rather than declaring the generic signature supported from INT64 alone.
        if (signature.arguments().size() == 2 &&
            signature.arguments().at(0).kind() == googlesql::ARG_KIND_EXPR_ANY_1 &&
            signature.arguments().at(1).kind() == googlesql::ARG_KIND_EXPR_ARRAY_ANY_1) {
          elements = {
              "2",
              "2.0",
              "NUMERIC '2'",
              "BIGNUMERIC '2'",
              "TRUE",
              "'abc'",
              "b'abc'",
              "DATE '2024-01-15'",
              "TIME '10:20:30'",
              "DATETIME '2024-01-15 10:20:30'",
              "TIMESTAMP '2024-01-15 10:20:30+00'",
              "INTERVAL 1 DAY",
              "RANGE<DATE> '[2024-01-01, 2024-02-01)'",
          };
        }
        for (const std::string& element : elements) {
          const auto query = GeneratedQuery(name, *function, signature, element);
          if (list_signatures) {
            std::cout << signature.DebugString(name) << "\n  "
                      << (std::holds_alternative<std::string>(query)
                              ? std::get<std::string>(query)
                              : std::get<Probe>(query).detail)
                      << "\n";
            continue;
          }
          probes.push_back(std::holds_alternative<std::string>(query)
                               ? RunProbe(emulator, tables, std::get<std::string>(query))
                               : std::get<Probe>(query));
        }
      }
    } else {
      probes.push_back({Outcome::kUnsupported, "the analyzer does not know this function"});
    }
    if (list_signatures || probes.empty()) {
      continue;
    }
    std::map<Outcome, int> counts;
    std::set<std::string> notes;
    for (const Probe& probe : probes) {
      ++counts[probe.outcome];
      if (probe.outcome != Outcome::kRuns) {
        notes.insert(probe.detail);
      }
    }
    const std::string_view status = Status(counts);
    ++totals[status];
    std::string note;
    if (const auto it = documented.find(name); it != documented.end()) {
      note = it->second;
    }
    for (const std::string& n : notes) {
      note += (note.empty() ? "" : "; ") + n;
    }
    rows << "| [`" << name << "`](" << kDocs << "/" << MainDoc(name, docs) << ") | "
         << Categories(docs) << " | " << status << " | " << implementation << " | " << Escape(note)
         << " |\n";
  }
  if (list_signatures) {
    return 0;
  }
  std::cout << kPreamble << "| Status | Functions |\n| --- | --- |\n";
  for (const auto& [status, count] : totals) {
    std::cout << "| " << status << " | " << count << " |\n";
  }
  std::cout << "\n| Function | Category | Status | Implementation | Notes |\n"
            << "| --- | --- | --- | --- | --- |\n"
            << rows.str();
  return 0;
}

}  // namespace
}  // namespace bigquery_emulator_duckdb

int main(int argc, char** argv) {
  try {
    return bigquery_emulator_duckdb::Main(argc, argv);
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  } catch (...) {
    std::cerr << "Unknown error\n";
    return 1;
  }
}
