// Probes the SQL features listed in tools/sql_features.txt against the emulator and prints a
// Markdown report of which ones translate and run. Each query runs on a fresh emulator holding the
// fixture tables the file's setup statements create. A probe checks only that a query translates
// and runs on DuckDB, not that it returns what BigQuery would; a note in the file describes
// behavior a probe cannot observe.

#include <iostream>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "src/api_error.h"
#include "src/catalog.h"
#include "src/emulator.h"
#include "tools/probe.h"

namespace bigquery_emulator_duckdb {
namespace {

constexpr std::string_view kPreamble = R"(# SQL feature support

<!-- Generated by //:sql_probe. Do not edit; run `just docs` to regenerate. -->

This page lists GoogleSQL statements and clauses and whether the emulator runs them. Built-in
functions are listed in [functions.md](functions.md).

`//:sql_probe` runs each query in `tools/sql_features.txt` on an emulator holding a few fixture
tables in the default dataset, `t (id INT64, name STRING, tags ARRAY<STRING>, s STRUCT<a INT64,
b STRING>)` and `u (id INT64, v INT64)`. A probe checks only that a query translates and runs on
DuckDB, not that it returns what BigQuery would. The notes the features file gives describe how
the emulator differs from BigQuery where a probe cannot observe it, and the probe's own notes name
what it rejected.

- **Supported**: every query runs.
- **Partial**: some queries run, and the emulator rejects the others as unsupported.
- **Unsupported**: the emulator rejects every query as unsupported.
- **Broken**: a query translates but fails on DuckDB, which is a bug.

)";

constexpr std::string_view kDataset = "d";

// The tables of an emulator, so that a probe analyzes against the fixture.
class EmulatorTables : public TableSource {
 public:
  explicit EmulatorTables(Emulator& emulator) : emulator_(emulator) {}

  std::optional<std::vector<FieldSchema>> FindTable(const std::string& project,
                                                    const std::string& dataset,
                                                    const std::string& table) override {
    try {
      return emulator_.GetTable({project, dataset, table}).schema;
    } catch (const ApiError&) {
      return std::nullopt;
    }
  }

 private:
  Emulator& emulator_;
};

struct Feature {
  std::string name;
  std::vector<std::string> queries;
  std::string note;
};

struct Section {
  std::string title;
  std::vector<Feature> features;
};

// Splits "NAME | TEXT" at the first separator.
std::optional<std::pair<std::string, std::string>> SplitNamed(const std::string& text) {
  const size_t separator = text.find(" | ");
  if (separator == std::string::npos || separator == 0 || separator + 3 == text.size()) {
    return std::nullopt;
  }
  return std::pair(text.substr(0, separator), text.substr(separator + 3));
}

int Main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "usage: sql_probe FEATURES_FILE\n";
    return 2;
  }
  std::vector<std::string> setup;
  std::vector<Section> sections;
  // Where each feature is, as indices into `sections` and its features.
  std::map<std::string, std::pair<size_t, size_t>> features;
  for (const auto& [directive, text] : ReadLines(argv[1])) {
    if (directive == "setup") {
      setup.push_back(text);
      continue;
    }
    if (directive == "section") {
      sections.push_back({text, {}});
      continue;
    }
    const auto named = SplitNamed(text);
    if ((directive != "query" && directive != "note") || !named || sections.empty()) {
      std::cerr << "cannot parse: " << directive << " " << text << "\n";
      return 1;
    }
    const auto& [name, value] = *named;
    if (!features.contains(name)) {
      if (directive == "note") {
        std::cerr << "note before the queries of " << name << "\n";
        return 1;
      }
      sections.back().features.push_back({name, {}, ""});
      features[name] = {sections.size() - 1, sections.back().features.size() - 1};
    }
    const auto [s, f] = features[name];
    Feature& feature = sections[s].features[f];
    if (directive == "query") {
      feature.queries.push_back(value);
    } else if (!feature.note.empty()) {
      std::cerr << "second note for " << name << "\n";
      return 1;
    } else {
      feature.note = value;
    }
  }

  std::map<std::string, int> totals;
  std::vector<std::string> untested;
  std::ostringstream body;
  for (const Section& section : sections) {
    body << "## " << section.title << "\n\n| Feature | Status | Notes |\n| --- | --- | --- |\n";
    for (const Feature& feature : section.features) {
      std::map<Outcome, int> counts;
      std::set<std::string> notes;
      for (const std::string& sql : feature.queries) {
        Emulator emulator;
        for (const std::string& statement : setup) {
          const auto job = emulator.RunQuery({.project_id = "test", .query = statement});
          if (job->error.has_value()) {
            std::cerr << "setup failed: " << statement << ": " << job->error->what() << "\n";
            return 1;
          }
        }
        EmulatorTables tables(emulator);
        const Probe probe = RunProbe(emulator, tables, sql, std::string(kDataset));
        ++counts[probe.outcome];
        if (probe.outcome == Outcome::kUntested) {
          untested.push_back(feature.name + ": " + probe.detail);
        } else if (probe.outcome != Outcome::kRuns) {
          notes.insert(probe.detail);
        }
      }
      const std::string status = Status(counts);
      ++totals[status];
      std::string note = feature.note;
      for (const std::string& n : notes) {
        note += (note.empty() ? "" : "; ") + n;
      }
      body << "| " << Escape(feature.name) << " | " << status << " | " << Escape(note) << " |\n";
    }
    body << "\n";
  }
  // Every query is written by hand, so one the analyzer rejects is a mistake in the file.
  if (!untested.empty()) {
    for (const std::string& message : untested) {
      std::cerr << "not valid GoogleSQL: " << message << "\n";
    }
    return 1;
  }
  std::cout << kPreamble << "| Status | Features |\n| --- | --- |\n";
  for (const auto& [status, count] : totals) {
    std::cout << "| " << status << " | " << count << " |\n";
  }
  std::string text = body.str();
  text.pop_back();  // The blank line after the last table.
  std::cout << "\n" << text;
  return 0;
}

}  // namespace
}  // namespace bigquery_emulator_duckdb

int main(int argc, char** argv) {
  try {
    return bigquery_emulator_duckdb::Main(argc, argv);
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  } catch (...) {
    std::cerr << "Unknown error\n";
    return 1;
  }
}
