#!/usr/bin/env bash
# Regenerates tools/bigquery_functions.txt from the function list in the BigQuery documentation,
# which is the only list of BigQuery's functions Google publishes. Conditional expressions such
# as IF are documented on a page of their own, so they are read from there.
set -euo pipefail

readonly base=https://docs.cloud.google.com/bigquery/docs/reference/standard-sql
readonly out="$(dirname "$0")/bigquery_functions.txt"

# Prints "NAME PAGE#ANCHOR" for every row of the function table on the page. A row starts with a
# link to the function, such as <td><a href="..."><code ...>NAME</code> (JSON)</a>, where the text
# after the name tells apart functions of the same name.
rows() {
  curl -fsSL "$base/$1" | tr '\n' ' ' |
    grep -oE '<td> *<a href="[^"]*"><code[^>]*>[A-Z][A-Z0-9_.]*</code>[^<]*</a>' |
    sed -E "s|<td> *<a href=\"(/bigquery/docs/reference/standard-sql/)?#?([^\"]*)\"><code[^>]*>([^<]*)</code>[^<]*</a>|\3 \2|" |
    sed -E "s| ([a-z_0-9-]*)$| $1#\1|"
}

{
  echo "# Generated by tools/update_bigquery_functions.sh from the BigQuery documentation."
  echo "# Each line is a function name and its page and anchor under $base. A name BigQuery"
  echo "# documents on several pages has a line for each."
  { rows functions-all; rows conditional_expressions; } | LC_ALL=C sort -u
} >"$out"
echo "wrote $(grep -vc '^#' "$out") functions to $out"
